import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:timezone/data/latest_all.dart' as tz_data;
import 'package:timezone/timezone.dart' as tz;

part 'notification_service.g.dart';

enum ReminderChannel {
  workout('workout_reminders', 'Workout Reminders', 'Nudges to keep your training schedule'),
  nutrition('nutrition_reminders', 'Nutrition Reminders', 'Meal and water logging reminders'),
  recovery('recovery_reminders', 'Recovery Reminders', 'Sleep, mobility, and rest day nudges'),
  aiInsight('ai_insights', 'AI Insights', 'Personalized coaching insights from your AI coaches');

  const ReminderChannel(this.id, this.name, this.description);
  final String id;
  final String name;
  final String description;
}

/// Thin wrapper around `flutter_local_notifications` for scheduled,
/// recurring, and one-off local reminders. Server-driven push (e.g. an AI
/// insight generated by an Edge Function on a schedule) is delivered via
/// Supabase Realtime + a local notification fired on receipt, reusing the
/// same channels defined here.
class NotificationService {
  NotificationService() : _plugin = FlutterLocalNotificationsPlugin();

  final FlutterLocalNotificationsPlugin _plugin;
  bool _initialized = false;

  Future<void> init() async {
    if (_initialized) return;
    tz_data.initializeTimeZones();

    const androidInit = AndroidInitializationSettings('@mipmap/ic_launcher');
    const iosInit = DarwinInitializationSettings(
      requestAlertPermission: false,
      requestBadgePermission: false,
      requestSoundPermission: false,
    );
    await _plugin.initialize(
      const InitializationSettings(android: androidInit, iOS: iosInit),
    );

    for (final channel in ReminderChannel.values) {
      await _plugin
          .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
          ?.createNotificationChannel(
            AndroidNotificationChannel(channel.id, channel.name, description: channel.description),
          );
    }
    _initialized = true;
  }

  Future<bool> requestPermissions() async {
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      final granted = await _plugin
          .resolvePlatformSpecificImplementation<IOSFlutterLocalNotificationsPlugin>()
          ?.requestPermissions(alert: true, badge: true, sound: true);
      return granted ?? false;
    }
    final granted = await _plugin
        .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
        ?.requestNotificationsPermission();
    return granted ?? false;
  }

  Future<void> scheduleDaily({
    required int id,
    required ReminderChannel channel,
    required String title,
    required String body,
    required ReminderTime time,
  }) async {
    await _plugin.zonedSchedule(
      id,
      title,
      body,
      _nextInstanceOfTime(time),
      NotificationDetails(
        android: AndroidNotificationDetails(channel.id, channel.name, channelDescription: channel.description),
        iOS: const DarwinNotificationDetails(),
      ),
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      matchDateTimeComponents: DateTimeComponents.time,
    );
  }

  Future<void> showNow({
    required int id,
    required ReminderChannel channel,
    required String title,
    required String body,
  }) {
    return _plugin.show(
      id,
      title,
      body,
      NotificationDetails(
        android: AndroidNotificationDetails(channel.id, channel.name, channelDescription: channel.description),
        iOS: const DarwinNotificationDetails(),
      ),
    );
  }

  Future<void> cancel(int id) => _plugin.cancel(id);

  Future<void> cancelAll() => _plugin.cancelAll();

  tz.TZDateTime _nextInstanceOfTime(ReminderTime time) {
    final now = tz.TZDateTime.now(tz.local);
    var scheduled = tz.TZDateTime(tz.local, now.year, now.month, now.day, time.hour, time.minute);
    if (scheduled.isBefore(now)) {
      scheduled = scheduled.add(const Duration(days: 1));
    }
    return scheduled;
  }
}

/// Deliberately distinct from `material.dart`'s `TimeOfDay` so this service
/// has no Flutter UI dependency and stays trivially unit-testable.
class ReminderTime {
  const ReminderTime({required this.hour, required this.minute});
  final int hour;
  final int minute;
}

@Riverpod(keepAlive: true)
NotificationService notificationService(Ref ref) => NotificationService();
